# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("todo.proto", :syntax => :proto3) do
    add_message "todo_package.TodoItemCreate" do
      optional :title, :string, 1
      optional :description, :string, 2
    end
    add_message "todo_package.TodoResponse" do
      optional :id, :int32, 1
      optional :title, :string, 2
      optional :description, :string, 3
    end
    add_message "todo_package.NoParams" do
    end
    add_message "todo_package.Todos" do
      repeated :todos, :message, 1, "todo_package.TodoResponse"
    end
  end
end

module TodoPackage
  TodoItemCreate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("todo_package.TodoItemCreate").msgclass
  TodoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("todo_package.TodoResponse").msgclass
  NoParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("todo_package.NoParams").msgclass
  Todos = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("todo_package.Todos").msgclass
end
