# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: todo.proto for package 'todo_package'

require 'grpc'
require_relative 'todo_pb'

module TodoPackage
  module TodoServices
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'todo_package.TodoServices'

      rpc :CreateTodo, ::TodoPackage::TodoItemCreate, ::TodoPackage::TodoResponse
      rpc :ReadTodo, ::TodoPackage::NoParams, ::TodoPackage::Todos
    end

    Stub = Service.rpc_stub_class
  end
end
